# Soil health study - Rwanda round 3

## Python practice

In [27]:
import pandas as pd
import numpy as np

# Load data

In [28]:
data = pd.read_csv("M&E - Soil Health Study - 18B Soil Health Study (created 2018-08-08) 2018-08-15.csv", na_values="---")

## Check out data

In [29]:
data.head()

,number,formid,form.start_time,form.enumerator_name,form.farmer_found,form.date,form.not_find_why,form.not_find_why_other,form.new_farmer,form.intro.intro,...,form.Farmer_phone,form.sample_id,form.name,form.gps_hidden,completed_time,started_time,username,received_on,form.case.@case_id,form.pretest
0,0,dd9d4051-af4f-4a6c-9977-f378d46921a6,12:04:00.000+02,Etienne_Ntakirutimana,0,NaN,deceased,NaN,0.0,NaN,...,.,614,Gasana Etiene,NaN,2018-07-17 12:04:43,2018-07-17 12:04:10,nru2,2018-07-17 10:05:12,c5ab213739bb406aa08c6a79f9885f49,NaN
1,1,386356e8-448e-4147-855d-434f00dbba06,15:31:00.000+02,Petit_Irene_Ntwari,1,2018-08-02,NaN,NaN,NaN,1.0,...,.,413,Misago J Bosco,-2.3273237 29.9219434 1378.4 9.0,2018-08-02 16:05:03,2018-08-02 15:31:44,nyz3,2018-08-06 04:41:46,597db3882baf4933857005f458278216,NaN
2,2,8b7a5d92-6a9b-4059-ac3e-fcb7c57c46e4,10:33:00.000+02,Petit_Irene_Ntwari,1,2018-08-02,NaN,NaN,NaN,1.0,...,782849664,416,Muhinda Thadeo,-2.319849 29.9105971 1486.19 9.5,2018-08-02 11:13:28,2018-08-02 10:37:20,nyz3,2018-08-06 04:41:41,63af2d65bab74a7b993bcb9c55f2c27e,NaN
3,3,1c09f5b6-c24f-4b5b-82df-ffbfee312969,08:13:00.000+01,Simeon_Hakuzimana,1,2018-08-02,NaN,NaN,NaN,1.0,...,.,783C,Hitiyaremye Pascasie,NaN,2018-08-06 11:43:39,2018-08-02 08:23:06,nym2,2018-08-06 09:44:40,7d034f3befbf44f6ae6150c95e5e346c,NaN
4,4,f31eacb2-3a19-4e18-b522-74f687b5c49a,11:13:00.000+01,Simeon_Hakuzimana,1,2018-08-06,NaN,NaN,NaN,1.0,...,.,1068C,Nyirahavugimana Libere,-2.4446157 29.2060169 0.0 4577.0,2018-08-06 11:47:30,2018-08-06 11:12:57,nym2,2018-08-06 09:48:23,28c6a09290be47a5b8880188f1471237,NaN

In [30]:
# column names
data.columns.values

array(['number', 'formid', 'form.start_time', 'form.enumerator_name',
       'form.farmer_found', 'form.date', 'form.not_find_why',
       'form.not_find_why_other', 'form.new_farmer', 'form.intro.intro',
       'form.d_paper_barcode', 'form.soil_id', 'form.soil_id2_',
       'form.same_id_scarnned', 'form.text_final.d_soilsample',
       'form.farmer.d_client18a', 'form.farmer.d_client18b',
       'form.farmer.d_client19a', 'form.farmer.district_18b',
       'form.farmer.cell_input_18b', 'form.farmer.cell_field_18b',
       'form.farmer.village_18b', 'form.farmer.farmer_name',
       'form.farmer.name_respondent', 'form.farmer.farmer_tel',
       'form.farmer.tel_respondent', 'form.farmer.neighbor_tel',
       'form.farmer.farmer_gender', 'form.farmer.respondent_gender',
       'form.farmer.age_farmer', 'form.farmer.age_respondent',
       'form.farmer.hh_n', 'form.n_cows', 'form.n_goats',
       'form.n_chickens', 'form.n_pigs', 'form.n_sheep',
       'form.soil_field.length_18b', 'form.soil_field.width_18b',
       'form.soil_field.n_spots_18b', 'form.prim_18a_.crop1_18A',
       'form.prim_18a_.seed_maize_crop1_18a',
       'form.prim_18a_.kg_seed_crop1_18a',
       'form.prim_18a_.yield_crop1_18a',
       'form.prim_18a_.crop1_yield_comparison_18b',
       'form.prim_18a_.crop2_18a', 'form.sec_18a_.seed_maize_crop2_18a',
       'form.sec_18a_.kg_seed_crop2_18a', 'form.sec_18a_.yield_crop2_18a',
       'form.sec_18a_.crop2_yield_comparison_18a',
       'form.ammend_18a_.fert1_18a', 'form.ammend_18a_.kg_fert1_18a',
       'form.ammend_18a_.fert2_18a', 'form.ammend_18a_.kg_fert2_18a',
       'form.ammend_18a_.compost_18a', 'form.ammend_18a_.kg_compost_18a',
       'form.ammend_18a_.compost_qual_18a',
       'form.ammend_18a_.compost_type_18a',
       'form.ammend_18a_.compost_other_18a', 'form.ammend_18a_.lime_18a',
       'form.ammend_18a_.kg_lime_18a', 'form.prim_18b_.crop1_18b',
       'form.prim_18b_.seed_maize_crop1_18b',
       'form.prim_18b_.kg_seed_crop1_18b', 'form.prim_18b_.yield_crop18b',
       'form.prim_18b_.crop1_yield_comparison_18b',
       'form.prim_18b_.crop2_18b', 'form.sec_18b_.seed_maize_crop1_18b',
       'form.sec_18b_.kg_seed_crop2_18b', 'form.sec_18b_.yield_crop2_18b',
       'form.sec_18b_.crop2_yield_comparison_18b',
       'form.ammend_18b_.fert1_18b',
       'form.ammend_18b_.kg_fert1_crop1_18b',
       'form.ammend_18b_.fert2_18b', 'form.ammend_18b_.kg_fert2_18b',
       'form.ammend_18b_.compost_18b', 'form.ammend_18b_.kg_compost_18b',
       'form.ammend_18b_.compost_qual_18b',
       'form.ammend_18b_.compost_type_18b',
       'form.ammend_18b_.compost_other_18b', 'form.ammend_18b_.lime_18b',
       'form.ammend_18b_.kg_lime_18b', 'form.crop_residues',
       'form.anti_erosion_efforts', 'form.n_types_crop_18b',
       'form.d_plant_rows_slope_18b', 'form.other_comments_',
       'form.finish_time', 'form.neighbor_or_voisin_phone',
       'form.Respondent_Phone', 'form.enumerator',
       'form.soil_field.field_ares', 'form.District', 'form.farmer_name',
       'form.Cell', 'form.Village', 'form.other_comments',
       'form.soil_field.field_area_18b', 'form.Description',
       'form.Respondent_17B', 'form.Farmer_phone', 'form.sample_id',
       'form.name', 'form.gps_hidden', 'completed_time', 'started_time',
       'username', 'received_on', 'form.case.@case_id', 'form.pretest'],
      dtype=object)

In [33]:
data.columns = data.columns.str.replace("form.", "") # change variable names quickly.
data.columns.values

array(['number', 'd', 'start_time', 'enumerator_name', 'farmer_found',
       'date', 'not_find_why', 'not_find_why_other', 'new_farmer',
       'intro.intro', 'd_paper_barcode', 'soil_id', 'soil_id2_',
       'same_id_scarnned', 'text_final.d_soilsample',
       'farmer.d_client18a', 'farmer.d_client18b', 'farmer.d_client19a',
       'farmer.district_18b', 'farmer.cell_input_18b',
       'farmer.cell_field_18b', 'farmer.village_18b',
       'farmer.farmer_name', 'farmer.name_respondent',
       'farmer.farmer_tel', 'farmer.tel_respondent',
       'farmer.neighbor_tel', 'farmer.farmer_gender',
       'farmer.respondent_gender', 'farmer.age_farmer',
       'farmer.age_respondent', 'farmer.hh_n', 'n_cows', 'n_goats',
       'n_chickens', 'n_pigs', 'n_sheep', 'soil_field.length_18b',
       'soil_field.width_18b', 'soil_field.n_spots_18b',
       'prim_18a_.crop1_18A', 'prim_18a_.seed_maize_crop1_18a',
       'prim_18a_.kg_seed_crop1_18a', 'prim_18a_.yield_crop1_18a',
       'prim_18a_.crop1_yield_comparison_18b', 'prim_18a_.crop2_18a',
       'sec_18a_.seed_maize_crop2_18a', 'sec_18a_.kg_seed_crop2_18a',
       'sec_18a_.yield_crop2_18a', 'sec_18a_.crop2_yield_comparison_18a',
       'ammend_18a_.fert1_18a', 'ammend_18a_.kg_fert1_18a',
       'ammend_18a_.fert2_18a', 'ammend_18a_.kg_fert2_18a',
       'ammend_18a_.compost_18a', 'ammend_18a_.kg_compost_18a',
       'ammend_18a_.compost_qual_18a', 'ammend_18a_.compost_type_18a',
       'ammend_18a_.compost_other_18a', 'ammend_18a_.lime_18a',
       'ammend_18a_.kg_lime_18a', 'prim_18b_.crop1_18b',
       'prim_18b_.seed_maize_crop1_18b', 'prim_18b_.kg_seed_crop1_18b',
       'prim_18b_.yield_crop18b', 'prim_18b_.crop1_yield_comparison_18b',
       'prim_18b_.crop2_18b', 'sec_18b_.seed_maize_crop1_18b',
       'sec_18b_.kg_seed_crop2_18b', 'sec_18b_.yield_crop2_18b',
       'sec_18b_.crop2_yield_comparison_18b', 'ammend_18b_.fert1_18b',
       'ammend_18b_.kg_fert1_crop1_18b', 'ammend_18b_.fert2_18b',
       'ammend_18b_.kg_fert2_18b', 'ammend_18b_.compost_18b',
       'ammend_18b_.kg_compost_18b', 'ammend_18b_.compost_qual_18b',
       'ammend_18b_.compost_type_18b', 'ammend_18b_.compost_other_18b',
       'ammend_18b_.lime_18b', 'ammend_18b_.kg_lime_18b', 'crop_residues',
       'anti_erosion_efforts', 'n_types_crop_18b',
       'd_plant_rows_slope_18b', 'other_comments_', 'finish_time',
       'neighbor_or_voisin_phone', 'Respondent_Phone', 'enumerator',
       'soil_field.field_ares', 'District', 'farmer_name', 'Cell',
       'Village', 'other_comments', 'soil_field.field_area_18b',
       'Description', 'Respondent_17B', 'Farmer_phone', 'sample_id',
       'name', 'gps_hidden', 'completed_time', 'started_time', 'username',
       'received_on', 'case.@case_id', 'pretest'], dtype=object)

It looks like most variables that should be numeric are string. Use some code to convert these.

In [31]:
data.dtypes

number                              int64
formid                             object
form.start_time                    object
form.enumerator_name               object
form.farmer_found                   int64
form.date                          object
form.not_find_why                  object
form.not_find_why_other            object
form.new_farmer                   float64
form.intro.intro                  float64
form.d_paper_barcode              float64
form.soil_id                       object
form.soil_id2_                     object
form.same_id_scarnned              object
form.text_final.d_soilsample      float64
form.farmer.d_client18a           float64
form.farmer.d_client18b           float64
form.farmer.d_client19a           float64
form.farmer.district_18b           object
form.farmer.cell_input_18b         object
form.farmer.cell_field_18b         object
form.farmer.village_18b            object
form.farmer.farmer_name            object
form.farmer.name_respondent        object
form.farmer.farmer_tel             object
form.farmer.tel_respondent         object
form.farmer.neighbor_tel           object
form.farmer.farmer_gender          object
form.farmer.respondent_gender      object
form.farmer.age_farmer            float64
                                   ...
form.ammend_18b_.lime_18b          object
form.ammend_18b_.kg_lime_18b      float64
form.crop_residues                 object
form.anti_erosion_efforts          object
form.n_types_crop_18b             float64
form.d_plant_rows_slope_18b        object
form.other_comments_               object
form.finish_time                   object
form.neighbor_or_voisin_phone     float64
form.Respondent_Phone              object
form.enumerator                    object
form.soil_field.field_ares        float64
form.District                      object
form.farmer_name                   object
form.Cell                          object
form.Village                       object
form.other_comments                object
form.soil_field.field_area_18b    float64
form.Description                   object
form.Respondent_17B               float64
form.Farmer_phone                  object
form.sample_id                     object
form.name                          object
form.gps_hidden                    object
completed_time                     object
started_time                       object
username                           object
received_on                        object
form.case.@case_id                 object
form.pretest                      float64
Length: 110, dtype: object

In [20]:
numeric_variables = data.select_dtypes(include="float64")
print data.shape, numeric_variables.shape

(701, 110) (701, 48)

Summarize all numeric variales:

In [25]:
data.describe(include="float64") # don't even have to subset the data beforehand

,form.new_farmer,form.intro.intro,form.d_paper_barcode,form.text_final.d_soilsample,form.farmer.d_client18a,form.farmer.d_client18b,form.farmer.d_client19a,form.farmer.age_farmer,form.farmer.age_respondent,form.farmer.hh_n,...,form.ammend_18b_.compost_18b,form.ammend_18b_.kg_compost_18b,form.ammend_18b_.compost_other_18b,form.ammend_18b_.kg_lime_18b,form.n_types_crop_18b,form.neighbor_or_voisin_phone,form.soil_field.field_ares,form.soil_field.field_area_18b,form.Respondent_17B,form.pretest
count,28.000000,694.000000,691.000000,691.000000,691.000000,691.000000,691.000000,691.000000,691.000000,691.000000,...,635.000000,344.000000,0.0,12.000000,635.000000,0.0,691.000000,691.000000,0.0,57.0
mean,0.750000,0.995677,0.063676,0.994211,0.519537,0.463097,0.547033,45.727931,49.515195,5.088278,...,0.541732,217.630814,NaN,71.375000,1.615748,NaN,6.238820,623.881957,NaN,0.0
std,0.440959,0.065653,0.244351,0.075918,0.499980,0.498998,0.498144,31.365098,15.540438,2.185464,...,0.498648,230.964097,NaN,87.741129,0.780522,NaN,8.584474,858.447405,NaN,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,-88.000000,1.000000,...,0.000000,15.000000,NaN,1.000000,1.000000,NaN,0.180000,18.000000,NaN,0.0
25%,0.750000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,38.000000,38.000000,3.000000,...,0.000000,100.000000,NaN,10.625000,1.000000,NaN,2.090000,209.000000,NaN,0.0
50%,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,51.000000,49.000000,5.000000,...,1.000000,150.000000,NaN,35.000000,1.000000,NaN,3.750000,375.000000,NaN,0.0
75%,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,61.000000,60.000000,7.000000,...,1.000000,250.000000,NaN,100.000000,2.000000,NaN,6.890000,689.000000,NaN,0.0
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,96.000000,96.000000,12.000000,...,1.000000,2000.000000,NaN,300.000000,4.000000,NaN,120.000000,12000.000000,NaN,0.0